# Generated by Django 3.0.8 on 2020-09-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20200902_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='movies'),
        ),
    ]
